### ISSUE TITLE
Slice out of bounds

### ISSUE THREAD

**Issue by Mazon** [m4tty/cajun#3]
Hello, i got this error? 

Removal-guide: http://www.malwareremovalguides.info/trovi-com-browser-hijacker-removal-guide/ IncidentType=malware Title=Adware/PUA: Trovi
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/m4tty/cajun.getFreeLinkLength(0xc820101180, 0x24c, 0x1fe, 0xc82056c288)
        /Users/hardy/src/github.com/m4tty/cajun/lexer.go:586 +0x276
github.com/m4tty/cajun.lexFreeLink(0xc82056c1b0, 0xc8200cd0f8)
        /Users/hardy/src/github.com/m4tty/cajun/lexer.go:323 +0x48
github.com/m4tty/cajun.(*lexer).nextItem(0xc82056c1b0, 0x0, 0x0, 0x0, 0x0)
        /Users/hardy/src/github.com/m4tty/cajun/lexer.go:133 +0xbf
github.com/m4tty/cajun.Transform(0xc820101180, 0x24c, 0x0, 0x0, 0x0, 0x0)
        /Users/hardy/src/github.com/m4tty/cajun/parser.go:199 +0x274
main.wikiCreoleToMarkdown(0xc820101180, 0x24c, 0x0, 0x0)
        /Users/hardy/src/niteowl/niteowl.go:266 +0x3b
main.createJiraTicket(0xc82072a3b0, 0x6, 0xed017f59b, 0xff9f358, 0xc8207

**Comment by Mazon** [comment]
Think not proper creole input is the issue..

**Comment by andyleap** [comment]
probably need more info about what's being passed in...
```
func main() {
	out, err := cajun.Transform(`Removal-guide: http://www.malwareremovalguides.info/trovi-com-browser-hijacker-removal-guide/ IncidentType=malware Title=Adware/PUA: Trovi`)
	fmt.Println(out, err)
}
```
yields
```
<p>Removal-guide: <a href="http://www.malwareremovalguides.info/trovi-com-browser-hijacker-removal-guide/" />http://www.malwareremovalguides.info/trovi-com-browser-hijacker-removal-guide/</a> IncidentType=malware Title=Adware/PUA: Trovi</p> <nil>
```
which seems correct.

**Comment by Mazon** [comment]
package main

import "fmt"
import "github.com/m4tty/cajun"

func main() {
        out, err := cajun.Transform(`Removal-guide: http://www.malwareremovalguides.info/trovi-com-browser-hijacker-removal-guide/`)
        fmt.Println(out, err)
}

**Comment by Mazon** [comment]
`
`func main() {
        out, err := cajun.Transform(`Removal-guide: http://www.malwareremovalguides.info/trovi-com-browser-hijacker-removal-guide/`)
        fmt.Println(out, err)
}`

When it is only the url, no 'space' or anything after it does not work. But the spec seem to allow it

[[link]]
[[MyBigPage|Go to my page]]
[[http://www.wikicreole.org/]]
http://www.rawlink.org/, http://www.another.rawlink.org
[[http://www.wikicreole.org/|Visit the WikiCreole website]]
[[Weird Stuff|**Weird** //Stuff//]]
[[Ohana:WikiFamily]]

**Comment by andyleap** [comment]
yeah, that's an issue in the parser.  I've got a pull request open that makes a few other changes as well, but does fix the issue.  https://github.com/m4tty/cajun/compare/master...andyleap:master#diff-afa30dddc22eee32cb8f633eef30e7f2R589 is where the fix is.

**Comment by Mazon** [comment]
Awesome dude! Thank you.
